import { config } from 'dotenv';
config();

const ATTRACTIVENESS = {
  QUESTIONS: process.env.ATTRACTIVENESS_QUESTIONS || '',
  RESULTS: process.env.ATTRACTIVENESS_RESULTS || '',
};

const YOUCOFFEE = {
  QUESTIONS: process.env.YOUCOFFEE_QUESTIONS || '',
  RESULTS: process.env.YOUCOFFEE_RESULTS || '',
};

const PERSONALITIES = {
  QUESTIONS: process.env.PERSONALITIES_QUESTIONS || '',
  RESULTS: process.env.PERSONALITIES_RESULTS || '',
  CALCULATOR: {
    RESULTS: process.env.PERSONALITIES_CALCULATOR_RESULTS || '',
    IDS: process.env.PERSONALITIES_CALCULATOR_IDS || '',
    DISCLAIMER: process.env.PERSONALITIES_CALCULATOR_DISCLAIMER || '',
    INFORMATION: process.env.PERSONALITIES_CALCULATOR_INFORMATION || '',
  },
};

const ROLE_IN_RELATIONSHIPS = {
  QUESTIONS: process.env.ROLE_IN_RELATIONSHIPS_QUESTIONS || '',
  INFORMATION: process.env.ROLE_IN_RELATIONSHIPS_INFORMATION || '',
  RESULTS: process.env.ROLE_IN_RELATIONSHIPS_RESULTS || '',
};

const TOXICAL_RELATIONSHIPS = {
  QUESTIONS: process.env.TOXICAL_RELATIONSHIPS_QUESTIONS || '',
  RESULTS: process.env.TOXICAL_RELATIONSHIPS_RESULTS || '',
  INFORMATION: process.env.TOXICAL_RELATIONSHIPS_INFORMATION || '',
};

const TRAUMATIC_EXPERIENCE = {
  QUESTIONS: process.env.TRAUMATIC_EXPERIENCE_QUESTIONS || '',
  RESULTS: process.env.TRAUMATIC_EXPERIENCE_RESULTS || '',
  INFORMATION: process.env.TRAUMATIC_EXPERIENCE_INFORMATION ?? '',
};

const BENEFIT_CONSULTATION = process.env.BENEFIT_CONSULTATION || '';

const ARRAY_OF_FILE_IDS = [
  BENEFIT_CONSULTATION,

  YOUCOFFEE.QUESTIONS,
  YOUCOFFEE.RESULTS,

  ATTRACTIVENESS.QUESTIONS,
  ATTRACTIVENESS.RESULTS,

  PERSONALITIES.QUESTIONS,
  PERSONALITIES.RESULTS,
  PERSONALITIES.CALCULATOR.DISCLAIMER,
  PERSONALITIES.CALCULATOR.IDS,
  PERSONALITIES.CALCULATOR.INFORMATION,
  PERSONALITIES.CALCULATOR.RESULTS,

  TOXICAL_RELATIONSHIPS.QUESTIONS,
  TOXICAL_RELATIONSHIPS.RESULTS,

  ROLE_IN_RELATIONSHIPS.INFORMATION,
  ROLE_IN_RELATIONSHIPS.QUESTIONS,
  ROLE_IN_RELATIONSHIPS.RESULTS,

  TOXICAL_RELATIONSHIPS.QUESTIONS,
  TOXICAL_RELATIONSHIPS.RESULTS,
  TOXICAL_RELATIONSHIPS.INFORMATION,

  TRAUMATIC_EXPERIENCE.QUESTIONS,
  TRAUMATIC_EXPERIENCE.RESULTS,
  TRAUMATIC_EXPERIENCE.INFORMATION,
];
export {
  ATTRACTIVENESS,
  PERSONALITIES,
  ROLE_IN_RELATIONSHIPS,
  TOXICAL_RELATIONSHIPS,
  TRAUMATIC_EXPERIENCE,
  ARRAY_OF_FILE_IDS,
  BENEFIT_CONSULTATION,
  YOUCOFFEE,
};
